### ISSUE TITLE
The Warrior class can be slightly better

### ISSUE THREAD

**Issue by yassa-tamer** [abdsaber000/War-Game#1]
It has a lot of repeated logic. Always keep your code DRY. Also, I'm not too fond of the idea that it can be initialized without initial values for the member vars.

**Comment by abdsaber000** [comment]
So in the constructor of Warrior , you recommend setting the other member variables to 0 ?

**Comment by yassa-tamer** [comment]
I suggest you:
* move the repeated logic into a separate routine.
* either remove the without-initial-values constructor or set initial values for these member vars.
* some testing would be recommended.

**Comment by yassa-tamer** [comment]
> So in the constructor of Warrior, you recommend setting the other member variables to 0 ?

Well, it depends on your overall design and requirements. If I were you I would remove this constructor. If in the future you need to create a Warrior without any params only then you can add this constructor (with proper initial vals for the member vars)

What do you think ? @abdsaber000

**Comment by abdsaber000** [comment]
check this commit 
https://github.com/abdsaber000/War-Game/commit/f34234d8a3b837adf61e5ca784093d87cfef1fd8

**Comment by yassa-tamer** [comment]
@abdsaber000 good job!
I left some comments.

Please create a PR instead of pushing to the master branch so that it is easy to review.

**Comment by abdsaber000** [comment]
Done.
See my latest commit.

**Comment by yassa-tamer** [comment]
LGTM

Nice work! you can close the issue.
